const AllStyles = {
  navigationBar: {
    display: 'flex',
    height: '48px',
    padding: '12px 5px',
    alignItems: 'center',
    gap: '12px',
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  navigationRight: {
    display: 'flex',
    justifyContent: 'space-between',
    width: '20%',
  },
  navigationLeft: {
    display: 'flex',
    justifyContent: 'space-between',
    width: '80%',
  },
  navigationName: {
    width: '85%',
    color: 'var(--Greyscale-900, #212121)',
    fontFamily: 'Urbanist',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '120%',
    textAlign: 'left',
  },
  homeBody: {
    textAlign: 'center',
  },
  homeRex: {
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    padding: '100px 0',
    // position: 'absolute',
  },
  ellipse: {
    background: 'linear-gradient(286deg, #6949FF 0%, #876DFF 100%)',
    position: 'fixed',
    zIndex: 0,
    width: 50,
    height: 50,
    borderRadius: '50%',
    // top: 100,
    // right: 100,
  },
  el1: {
    top: 20,
    right: 30,
  },
  el2: {
    top: 40,
    right: 50,
  },
  el3: {
    top: 90,
    right: 40,
  },
  el4: {
    top: 63,
    right: 70,
  },
  el5: {
    top: 20,
    right: 30,
  },
  el6: {
    top: 100,
    right: 30,
  },
  el7: {
    top: 300,
    right: 400,
  },
  el8: {
    top: 270,
    right: 390,
  },
  el9: {
    top: 500,
    left: 360,
  },
  el10: {
    top: 90,
    left: 10,
  },
  el11: {
    top: 750,
    left: 30,
  },
  el12: {
    top: 230,
    left: 50,
  },
  el13: {
    top: 300,
    left: 80,
  },
  el14: {
    top: 500,
    left: 90,
  },
  el15: {
    top: 60,
    left: 60,
  },
  el16: {
    top: 450,
    left: 180,
  },
  greetings: {
    display: 'flex',
    color: 'var(--Greyscale-900, #212121)',
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'Urbanist',
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '120%',
    margin: '50px 0',
  },
  message: {
    color: 'var(--Greyscale-900, #212121)',
    textAlign: 'center',
    fontFamily: 'Urbanist',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 1000,
    lineHeight: '120%',
    margin: '0 0 15px 0',
  },
  message2: {
    color: 'var(--Greyscale-900, #212121)',
    textAlign: 'center',
    fontFamily: 'Satoshi',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '140%',
    letterSpacing: '0.2px',
    margin: '0 0 32px 0',
  },
  startChatButton: {
    display: 'flex',
    padding: '18px 16px',
    margin: '16px',
    borderRadius: '100px',
    background: 'var(--Primary-500, #6949FF)',
    boxShadow: '4px 8px 24px 0px rgba(0, 205, 189, 0.25)',
    height: '22px',
    ':hover': {
      textDecoration: 'none',
    },
    width: '83%', 
  },
  startChatButtonText: {
    width: '100%',
    color: 'var(--Others-White, #FFF)',
    textShadow: '4px 8px 24px rgba(0, 205, 189, 0.25)',
    fontFamily: 'Urbanist',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '140%',
    letterSpacing: '0.2px',
    textDecoration: 'none',
    textAlign: 'center',
    ':hover': {
      textDecoration: 'none',
    },
  },
  endedChats: {
    color: 'var(--Greyscale-900, #212121)',
    fontFamily: 'Satoshi',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '120%',
    textAlign: 'left',
  },
  seeAllLink: {
    color: 'var(--Primary-500, #6949FF)',
    textAlign: 'right',
    fontFamily: 'Satoshi',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '140%',
    letterSpacing: '0.2px',
    textDecoration: 'none',
  }, 
  endedChatsTitle: {
    display: 'flex', 
    flexDirection: 'row', 
    justifyContent: 'space-between',
    padding: '24px 0',
  }, 
  endedChatsBody: {
    display: 'flex',
    flexDirection: 'column', 
    gap: '24px', 
  }, 
  startAnotherChatButtonGrid: {
    display: 'flex',
    padding: '24px 24px 36px 24px',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '24px',
    borderRadius: '24px 24px 0px 0px',
    border: '1px solid var(--Greyscale-100, #F5F5F5)',
    background: 'var(--Others-White, #FFF)',
  },
};

export default AllStyles;
